	DE1_SoC_QSYS u0 (
		.audio2fifo_0_data_divfrec_export              (<connected-to-audio2fifo_0_data_divfrec_export>),              //       audio2fifo_0_data_divfrec.export
		.audio2fifo_0_empty_export                     (<connected-to-audio2fifo_0_empty_export>),                     //              audio2fifo_0_empty.export
		.audio2fifo_0_fifo_full_export                 (<connected-to-audio2fifo_0_fifo_full_export>),                 //          audio2fifo_0_fifo_full.export
		.audio2fifo_0_fifo_used_export                 (<connected-to-audio2fifo_0_fifo_used_export>),                 //          audio2fifo_0_fifo_used.export
		.audio2fifo_0_out_data_audio_export            (<connected-to-audio2fifo_0_out_data_audio_export>),            //     audio2fifo_0_out_data_audio.export
		.audio2fifo_0_out_pause_export                 (<connected-to-audio2fifo_0_out_pause_export>),                 //          audio2fifo_0_out_pause.export
		.audio2fifo_0_out_stop_export                  (<connected-to-audio2fifo_0_out_stop_export>),                  //           audio2fifo_0_out_stop.export
		.audio2fifo_0_wrclk_export                     (<connected-to-audio2fifo_0_wrclk_export>),                     //              audio2fifo_0_wrclk.export
		.audio2fifo_0_wrreq_export                     (<connected-to-audio2fifo_0_wrreq_export>),                     //              audio2fifo_0_wrreq.export
		.audio_sel_export                              (<connected-to-audio_sel_export>),                              //                       audio_sel.export
		.clk_clk                                       (<connected-to-clk_clk>),                                       //                             clk.clk
		.clk_25_out_clk                                (<connected-to-clk_25_out_clk>),                                //                      clk_25_out.clk
		.clk_sdram_clk                                 (<connected-to-clk_sdram_clk>),                                 //                       clk_sdram.clk
		.div_freq_export                               (<connected-to-div_freq_export>),                               //                        div_freq.export
		.key_external_connection_export                (<connected-to-key_external_connection_export>),                //         key_external_connection.export
		.keyboard_keys_export                          (<connected-to-keyboard_keys_export>),                          //                   keyboard_keys.export
		.modulation_selector_export                    (<connected-to-modulation_selector_export>),                    //             modulation_selector.export
		.mouse_pos_export                              (<connected-to-mouse_pos_export>),                              //                       mouse_pos.export
		.pll_locked_export                             (<connected-to-pll_locked_export>),                             //                      pll_locked.export
		.reset_reset_n                                 (<connected-to-reset_reset_n>),                                 //                           reset.reset_n
		.sdram_wire_addr                               (<connected-to-sdram_wire_addr>),                               //                      sdram_wire.addr
		.sdram_wire_ba                                 (<connected-to-sdram_wire_ba>),                                 //                                .ba
		.sdram_wire_cas_n                              (<connected-to-sdram_wire_cas_n>),                              //                                .cas_n
		.sdram_wire_cke                                (<connected-to-sdram_wire_cke>),                                //                                .cke
		.sdram_wire_cs_n                               (<connected-to-sdram_wire_cs_n>),                               //                                .cs_n
		.sdram_wire_dq                                 (<connected-to-sdram_wire_dq>),                                 //                                .dq
		.sdram_wire_dqm                                (<connected-to-sdram_wire_dqm>),                                //                                .dqm
		.sdram_wire_ras_n                              (<connected-to-sdram_wire_ras_n>),                              //                                .ras_n
		.sdram_wire_we_n                               (<connected-to-sdram_wire_we_n>),                               //                                .we_n
		.signal_selector_export                        (<connected-to-signal_selector_export>),                        //                 signal_selector.export
		.vga_alt_vip_itc_0_clocked_video_vid_clk       (<connected-to-vga_alt_vip_itc_0_clocked_video_vid_clk>),       // vga_alt_vip_itc_0_clocked_video.vid_clk
		.vga_alt_vip_itc_0_clocked_video_vid_data      (<connected-to-vga_alt_vip_itc_0_clocked_video_vid_data>),      //                                .vid_data
		.vga_alt_vip_itc_0_clocked_video_underflow     (<connected-to-vga_alt_vip_itc_0_clocked_video_underflow>),     //                                .underflow
		.vga_alt_vip_itc_0_clocked_video_vid_datavalid (<connected-to-vga_alt_vip_itc_0_clocked_video_vid_datavalid>), //                                .vid_datavalid
		.vga_alt_vip_itc_0_clocked_video_vid_v_sync    (<connected-to-vga_alt_vip_itc_0_clocked_video_vid_v_sync>),    //                                .vid_v_sync
		.vga_alt_vip_itc_0_clocked_video_vid_h_sync    (<connected-to-vga_alt_vip_itc_0_clocked_video_vid_h_sync>),    //                                .vid_h_sync
		.vga_alt_vip_itc_0_clocked_video_vid_f         (<connected-to-vga_alt_vip_itc_0_clocked_video_vid_f>),         //                                .vid_f
		.vga_alt_vip_itc_0_clocked_video_vid_h         (<connected-to-vga_alt_vip_itc_0_clocked_video_vid_h>),         //                                .vid_h
		.vga_alt_vip_itc_0_clocked_video_vid_v         (<connected-to-vga_alt_vip_itc_0_clocked_video_vid_v>),         //                                .vid_v
		.vga_vga_clk_clk                               (<connected-to-vga_vga_clk_clk>)                                //                     vga_vga_clk.clk
	);

